services:
  izvod:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data/input:/data/input
      - ./data/processed:/data/processed
      - ./data/output:/data/output
      - ./data/db:/data/db
      - ./data/log:/data/log
    environment:
      - IZVOD_SCAN_INTERVAL=60
